# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "dev-app1" do |dev-app1|
    dev-app1.vm.box = "centos/7"
    dev-app1.vm.hostname = "dev-app1"
    dev-app1.vm.network "private_network", ip: "192.168.33.200"
    dev-app1.vm.network "forwarded_port", guest: 80, host: 8080
    dev-app1.vm.network "forwarded_port", guest: 9090, host: 9090
  end

  config.vm.define "dev-db1" do |dev-db1|
    dev-db1.vm.box = "centos/7"
    dev-db1.vm.hostname = "dev-db1"
    dev-db1.vm.network "private_network", ip: "192.168.122.100"
    dev-db1.vm.network "forwarded_port", guest: 1521, host: 1521
  end

end
