---
- name: Install VirtualBox Dependences
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - make
    - patch
    - dkms
    - qt
    - libgomp
    - kernel-headers
    - kernel-devel
    - fontforge
    - binutils
    - glibc-headers
    - glibc-devel
  become: true
  when: ansible_os_family == "RedHat"
- name: Download VirtualBox Repository
  get_url:
    url: http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
    dest: /etc/yum.repos.d
    mode: 0644
  become: true
  when: ansible_os_family == "RedHat"
  run_once: true

- name: Install VirtualBox
  command: yum install -y VirtualBox-5.1
  become: true
  when: ansible_os_family == "RedHat"


#  - name: Update Repository List
#    command: sudo {{ item }}
#    with_items: 
#     - rm -fr /var/cache/yum/*
#     - yum clean all
#     - yum repolist   
#    when: ansible_os_family == "RedHat"

- name: Install VirtualBox
  command: yum install -y VirtualBox-5.1
  become: true
  when: ansible_os_family == "RedHat"

#  - name: Install VirtualBox
#    yum: name=VirtualBox-5.1 state=present
#    become: true
#    when: ansible_os_family == "RedHat"

- name: Check that you have the kernel sources downloaded for your running kernel version (if they don't match you might need to yum update and reboot)
  command: echo {{ item }}
  with_items: 
   - ls /usr/src/kernels/
   - uname -r
  become: true
  when: ansible_os_family == "RedHat"

- name: Build the VirtualBox kernel module 
  command: echo {{ item }}
  with_items: 
   - export KERN_DIR=/usr/src/kernels/$(uname -r)
   - /sbin/rcvboxdrv setup
  become: true
  when: ansible_os_family == "RedHat"